apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      containers:
        - name: todo-backend
          image: vinitparmar03/todo_backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: PORT

            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: MONGODB_URL
          
          livenessProbe:
            httpGet:
              path: /api/v1/health/live
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /api/v1/health/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2