services:
  frontend:
    image: vinitparmar03/todo_frontend:v2
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://todo.local/api/v1

  backend:
    image: vinitparmar03/todo_backend:v2
    build:
      context: ./backend
      dockerfile: Dockerfile